name: individual-state-tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * 0

jobs:
  individual_states:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [focal]
        state:
          - mat.python2-packages
          - mat.python3-packages
          - mat.tools

    container:
      image: docker://digitalsleuth/mat-salt-tester:focal

    steps:
      - uses: actions/checkout@master
      - name: test-state
        run: |
          salt-call -l info --file-root . --local --retcode-passthrough --state-output=mixed state.sls ${{ matrix.state }} pillar="{mat_user: root}"
